name: Production Deploy

# Trigger on a schedule (every 3 days) and allow manual trigger
on:
  schedule:
    - cron: '0 0 */3 * *'  # At 00:00 UTC every 3rd day
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Vercel Production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Vercel (Production)
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          npx vercel --prod --yes
